name: pillow
description: "Health Tracking App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number is used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.6.0
  go_router: ^14.7.2
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  percent_indicator: ^4.2.4
  pretty_animated_text: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  fl_chart: ^0.65.0
  tflite_flutter: ^0.11.0
  pdf: ^3.10.7
  share_plus: ^7.2.1
  flutter_local_notifications: ^19.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  timezone: ^0.9.2

dependency_overrides:
  timezone: ^0.9.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "C:/Projects/pillow/assets/icons/launcher.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/models/
    - assets/models/symptom_prediction/model.tflite
    - assets/models/symptom_prediction/tokenizer.json
    - assets/models/symptom_prediction/mlb.json

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit.ttf
